// auth_samples_nextjs/components/LoadingState.tsx
"use client";

export function LoadingState({ title, subtitle }: { title: string; subtitle: string }) {
  return (
    <div className="loading">
      <div className="spinner" />
      <div>
        <h2 className="card-title">{title}</h2>
        <p className="muted">{subtitle}</p>
      </div>
    </div>
  );
}

// auth_samples_angular/src/app/components/loading-state/loading-state.component.ts
import { Component, input } from "@angular/core";

@Component({
  selector: "app-loading-state",
  standalone: true,
  template: `
    <div class="loading">
      <div class="spinner"></div>
      <div>
        <h2 class="card-title">{{ title() }}</h2>
        <p class="muted">{{ subtitle() }}</p>
      </div>
    </div>
  `,
})
export class LoadingStateComponent {
  title = input.required<string>();
  subtitle = input.required<string>();
}
