// auth_samples_nextjs/app/not-found.tsx
"use client";

import { useRouter } from "next/navigation";
import { Shell } from "../components/Shell";
import { Card } from "../components/Card";

export default function NotFound() {
  const router = useRouter();
  return (
    <Shell status={{ label: "Route not found", tone: "neutral" }}>
      <Card>
        <div className="stack">
          <div className="status status-bad">404</div>
          <h2 className="card-title">This route doesn't exist.</h2>
          <p className="muted">Return to the login page to start a new session.</p>
          <button className="button ghost" onClick={() => router.replace("/")}>
            Go home
          </button>
        </div>
      </Card>
    </Shell>
  );
}

// auth_samples_vue3/src/views/NotFound.vue
<script setup lang="ts">
import { useRouter } from 'vue-router';
import Shell from '../components/Shell.vue';
import Card from '../components/Card.vue';

const router = useRouter();
</script>

<template>
  <Shell :status="{ label: 'Route not found', tone: 'neutral' }">
    <Card>
      <div class="stack">
        <div class="status status-bad">404</div>
        <h2 class="card-title">This route doesn't exist.</h2>
        <p class="muted">Return to the login page to start a new session.</p>
        <button class="button ghost" @click="router.replace('/')">
          Go home
        </button>
      </div>
    </Card>
  </Shell>
</template>
