// auth_samples_vue3/src/components/LoginView.vue
<script setup lang="ts">
import Card from './Card.vue';
import Feature from './Feature.vue';

defineProps<{
  error: string | null;
}>();

const emit = defineEmits<{
  (e: 'login'): void;
}>();
</script>

<template>
  <div class="stack">
    <Card>
      <div class="card-header">
        <span class="eyebrow">OAuth 2.1 + OpenID Connect</span>
        <h2 class="card-title">Sign in to continue</h2>
        <p class="muted">
          This app uses the authorization code flow with PKCE to fetch tokens securely for a
          browser-based client.
        </p>
      </div>
      <div class="button-row">
        <button class="button primary" @click="emit('login')">
          Continue with Tuurio ID
        </button>
        <span class="helper">You'll be redirected to test.id.tuurio.com</span>
      </div>
      <div v-if="error" class="status status-bad">{{ error }}</div>
    </Card>
    <Card tone="soft">
      <div class="feature-grid">
        <Feature title="PKCE by default" body="Proof Key for Code Exchange protects the code flow." />
        <Feature title="Short-lived tokens" body="Access tokens are scoped to openid profile email." />
        <Feature title="Session aware" body="Token state is persisted in session storage." />
      </div>
    </Card>
  </div>
</template>

// auth_samples_nextjs/components/LoginView.tsx
"use client";

import { Card } from "./Card";
import { Feature } from "./Feature";

export function LoginView({
  onLogin,
  error,
}: {
  onLogin: () => Promise<void>;
  error: string | null;
}) {
  return (
    <div className="stack">
      <Card>
        <div className="card-header">
          <span className="eyebrow">OAuth 2.1 + OpenID Connect</span>
          <h2 className="card-title">Sign in to continue</h2>
          <p className="muted">
            This app uses the authorization code flow with PKCE to fetch tokens securely for a
            browser-based client.
          </p>
        </div>
        <div className="button-row">
          <button className="button primary" onClick={onLogin}>
            Continue with Tuurio ID
          </button>
          <span className="helper">You'll be redirected to test.id.tuurio.com</span>
        </div>
        {error ? <div className="status status-bad">{error}</div> : null}
      </Card>
      <Card tone="soft">
        <div className="feature-grid">
          <Feature title="PKCE by default" body="Proof Key for Code Exchange protects the code flow." />
          <Feature title="Short-lived tokens" body="Access tokens are scoped to openid profile email." />
          <Feature title="Session aware" body="Token state is persisted in session storage." />
        </div>
      </Card>
    </div>
  );
}
