// auth_samples_angular/src/app/components/shell/shell.component.ts
import { Component, input } from "@angular/core";

export type ShellTone = "good" | "neutral";
export type ShellStatus = { label: string; tone: ShellTone };

@Component({
  selector: "app-shell",
  standalone: true,
  template: `
    <div class="app">
      <aside class="side-panel">
        <div class="brand">
          <div class="logo-mark">tu</div>
          <div>
            <p class="brand-name">Tuurio Auth Studio</p>
            <p class="brand-subtitle">OIDC playground for OAuth 2.1</p>
          </div>
        </div>
        <div class="side-card">
          <h1>Design for secure sign-in.</h1>
          <p class="muted">
            A minimal Angular client that signs in with OpenID Connect, displays decoded tokens,
            and supports secure logout redirects.
          </p>
          <div class="status-row">
            <span
              class="status"
              [class.status-good]="status().tone === 'good'"
              [class.status-neutral]="status().tone === 'neutral'"
            >
              {{ status().label }}
            </span>
            <span class="muted">Authority: test.id.tuurio.com</span>
          </div>
        </div>
        <div class="side-list">
          <div>
            <span class="eyebrow">Architecture</span>
            <p>Authorization code flow + PKCE</p>
          </div>
          <div>
            <span class="eyebrow">Storage</span>
            <p>Session storage for tokens</p>
          </div>
          <div>
            <span class="eyebrow">Scope</span>
            <p>openid profile email</p>
          </div>
        </div>
      </aside>
      <main class="main-panel">
        <ng-content />
      </main>
    </div>
  `,
})
export class ShellComponent {
  status = input.required<ShellStatus>();
}

// auth_samples_nextjs/components/Shell.tsx
"use client";

import type { ReactNode } from "react";

export type ShellStatus = { label: string; tone: "good" | "neutral" };

export function Shell({ children, status }: { children: ReactNode; status: ShellStatus }) {
  return (
    <div className="app">
      <aside className="side-panel">
        <div className="brand">
          <div className="logo-mark">tu</div>
          <div>
            <p className="brand-name">Tuurio Auth Studio</p>
            <p className="brand-subtitle">OIDC playground for OAuth 2.1</p>
          </div>
        </div>
        <div className="side-card">
          <h1>Design for secure sign-in.</h1>
          <p className="muted">
            A minimal Next.js client that signs in with OpenID Connect, displays decoded tokens,
            and supports secure logout redirects.
          </p>
          <div className="status-row">
            <span className={`status status-${status.tone}`}>{status.label}</span>
            <span className="muted">Authority: test.id.tuurio.com</span>
          </div>
        </div>
        <div className="side-list">
          <div>
            <span className="eyebrow">Architecture</span>
            <p>Authorization code flow + PKCE</p>
          </div>
          <div>
            <span className="eyebrow">Storage</span>
            <p>Session storage for tokens</p>
          </div>
          <div>
            <span className="eyebrow">Scope</span>
            <p>openid profile email</p>
          </div>
        </div>
      </aside>
      <main className="main-panel">{children}</main>
    </div>
  );
}
