// auth_samples_vue3/src/views/NotFound.vue
<script setup lang="ts">
import { useRouter } from 'vue-router';
import Shell from '../components/Shell.vue';
import Card from '../components/Card.vue';

const router = useRouter();
</script>

<template>
  <Shell :status="{ label: 'Route not found', tone: 'neutral' }">
    <Card>
      <div class="stack">
        <div class="status status-bad">404</div>
        <h2 class="card-title">This route doesn't exist.</h2>
        <p class="muted">Return to the login page to start a new session.</p>
        <button class="button ghost" @click="router.replace('/')">
          Go home
        </button>
      </div>
    </Card>
  </Shell>
</template>

// auth_samples_angular/src/app/not-found/not-found.component.ts
import { Component, inject } from "@angular/core";
import { Router } from "@angular/router";
import { CardComponent } from "../components/card/card.component";
import { ShellComponent } from "../components/shell/shell.component";

@Component({
  selector: "app-not-found",
  standalone: true,
  imports: [ShellComponent, CardComponent],
  template: `
    <app-shell [status]="{ label: 'Route not found', tone: 'neutral' }">
      <app-card>
        <div class="stack">
          <div class="status status-bad">404</div>
          <h2 class="card-title">This route doesn't exist.</h2>
          <p class="muted">Return to the login page to start a new session.</p>
          <button class="button ghost" type="button" (click)="goHome()">
            Go home
          </button>
        </div>
      </app-card>
    </app-shell>
  `,
})
export class NotFoundComponent {
  private readonly router = inject(Router);

  goHome() {
    this.router.navigateByUrl("/", { replaceUrl: true });
  }
}
