// auth_samples_angular/src/app/components/token-panel/token-panel.component.ts
import { Component, input, signal } from "@angular/core";
import { JsonPipe } from "@angular/common";
import { CardComponent } from "../card/card.component";

@Component({
  selector: "app-token-panel",
  standalone: true,
  imports: [CardComponent, JsonPipe],
  template: `
    <app-card>
      <div class="section-header">
        <div class="section-icon">{{ title() === 'Access Token' ? 'AT' : 'ID' }}</div>
        <div>
          <h3 class="section-title">{{ title() }}</h3>
          <p class="muted">{{ description() }}</p>
        </div>
      </div>
      <details class="token-details">
        <summary class="token-summary">
          <span class="eyebrow">Raw JWT</span>
          <code class="token-preview">{{ token() ? `${token().slice(0, 48)}...` : "Not provided" }}</code>
        </summary>
        <pre class="token-block">{{ token() || "Not provided" }}</pre>
      </details>
      <div class="panel-header">
        <span class="eyebrow">Decoded payload</span>
        <button class="button small ghost" type="button" (click)="copy()" [disabled]="!token()">
          {{ copied() ? "Copied" : "Copy" }}
        </button>
      </div>
      <div class="token-claims">
        <pre class="code-block">{{ decoded() ? (decoded() | json) : "Not a JWT or unable to decode." }}</pre>
      </div>
    </app-card>
  `,
})
export class TokenPanelComponent {
  title = input.required<string>();
  token = input.required<string>();
  decoded = input<Record<string, unknown> | null>(null);
  description = input.required<string>();

  copied = signal(false);

  async copy() {
    if (!navigator.clipboard || !this.token()) return;
    await navigator.clipboard.writeText(this.token());
    this.copied.set(true);
    window.setTimeout(() => this.copied.set(false), 1800);
  }
}

// auth_samples_vue3/src/components/TokenPanel.vue
<script setup lang="ts">
import { ref } from 'vue';
import Card from './Card.vue';

const props = defineProps<{
  title: string;
  token: string | undefined;
  decoded: Record<string, unknown> | null;
  description: string;
}>();

const copied = ref(false);

const handleCopy = async () => {
  if (!navigator.clipboard || !props.token) return;
  await navigator.clipboard.writeText(props.token);
  copied.value = true;
  window.setTimeout(() => copied.value = false, 1800);
};
</script>

<template>
  <Card>
    <div class="section-header">
      <div class="section-icon">{{ title === 'Access Token' ? 'AT' : 'ID' }}</div>
      <div>
        <h3 class="section-title">{{ title }}</h3>
        <p class="muted">{{ description }}</p>
      </div>
    </div>
    <details class="token-details">
      <summary class="token-summary">
        <span class="eyebrow">Raw JWT</span>
        <code class="token-preview">{{ token ? `${token.slice(0, 48)}...` : "Not provided" }}</code>
      </summary>
      <pre class="token-block">{{ token || "Not provided" }}</pre>
    </details>
    <div class="panel-header">
      <span class="eyebrow">Decoded payload</span>
      <button class="button small ghost" @click="handleCopy" :disabled="!token">
        {{ copied ? "Copied" : "Copy" }}
      </button>
    </div>
    <div class="token-claims">
      <pre class="code-block">{{ decoded ? JSON.stringify(decoded, null, 2) : "Not a JWT or unable to decode." }}</pre>
    </div>
  </Card>
</template>
