// auth_samples_nextjs/components/TokenPanel.tsx
"use client";

import { useState } from "react";
import { Card } from "./Card";

export function TokenPanel({
  title,
  token,
  decoded,
  description,
}: {
  title: string;
  token: string;
  decoded: Record<string, unknown> | null;
  description: string;
}) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    if (!navigator.clipboard || !token) return;
    await navigator.clipboard.writeText(token);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1800);
  };

  return (
    <Card tone="panel">
      <div className="panel-header">
        <div>
          <h3 className="panel-title">{title}</h3>
          <p className="muted">{description}</p>
        </div>
        <button className="button small ghost" onClick={handleCopy} disabled={!token}>
          {copied ? "Copied" : "Copy"}
        </button>
      </div>
      <pre className="token-block">{token || "Not provided"}</pre>
      <div className="token-claims">
        <span className="eyebrow">Decoded claims</span>
        <pre className="code-block">
          {decoded ? JSON.stringify(decoded, null, 2) : "Not a JWT or unable to decode."}
        </pre>
      </div>
    </Card>
  );
}

// auth_samples_vue3/src/components/TokenPanel.vue
<script setup lang="ts">
import { ref } from 'vue';
import Card from './Card.vue';

const props = defineProps<{
  title: string;
  token: string | undefined;
  decoded: Record<string, unknown> | null;
  description: string;
}>();

const copied = ref(false);

const handleCopy = async () => {
  if (!navigator.clipboard || !props.token) return;
  await navigator.clipboard.writeText(props.token);
  copied.value = true;
  window.setTimeout(() => copied.value = false, 1800);
};
</script>

<template>
  <Card tone="panel">
    <div class="panel-header">
      <div>
        <h3 class="panel-title">{{ title }}</h3>
        <p class="muted">{{ description }}</p>
      </div>
      <button class="button small ghost" @click="handleCopy" :disabled="!token">
        {{ copied ? "Copied" : "Copy" }}
      </button>
    </div>
    <pre class="token-block">{{ token || "Not provided" }}</pre>
    <div class="token-claims">
      <span class="eyebrow">Decoded claims</span>
      <pre class="code-block">{{ decoded ? JSON.stringify(decoded, null, 2) : "Not a JWT or unable to decode." }}</pre>
    </div>
  </Card>
</template>
