// auth_samples_vue3/src/views/AuthCallback.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { useAuth } from '../composables/useAuth';
import Shell from '../components/Shell.vue';
import Card from '../components/Card.vue';
import LoadingState from '../components/LoadingState.vue';

const router = useRouter();
const { handleCallback } = useAuth();
const error = ref<string | null>(null);

onMounted(() => {
    handleCallback()
      .then(() => {
        router.replace("/");
      })
      .catch((err) => {
        error.value = err instanceof Error ? err.message : "Login failed.";
      });
});
</script>

<template>
  <Shell :status="{ label: 'Finalizing login', tone: 'neutral' }">
    <Card>
      <div v-if="error" class="stack">
        <div class="status status-bad">Authentication error</div>
        <h2 class="card-title">We couldn't finish signing you in.</h2>
        <p class="muted">{{ error }}</p>
        <button class="button ghost" @click="router.replace('/')">
          Back to login
        </button>
      </div>
      <LoadingState v-else title="Completing sign-in" subtitle="Processing the authorization response." />
    </Card>
  </Shell>
</template>

// auth_samples_angular/src/app/auth-callback/auth-callback.component.ts
import { Component, OnInit, inject, signal } from "@angular/core";
import { Router } from "@angular/router";
import { AuthService } from "../auth/auth.service";
import { CardComponent } from "../components/card/card.component";
import { LoadingStateComponent } from "../components/loading-state/loading-state.component";
import { ShellComponent } from "../components/shell/shell.component";

@Component({
  selector: "app-auth-callback",
  standalone: true,
  imports: [ShellComponent, CardComponent, LoadingStateComponent],
  template: `
    <app-shell [status]="{ label: 'Finalizing login', tone: 'neutral' }">
      <app-card>
        @if (error()) {
          <div class="stack">
            <div class="status status-bad">Authentication error</div>
            <h2 class="card-title">We couldn't finish signing you in.</h2>
            <p class="muted">{{ error() }}</p>
            <button class="button ghost" type="button" (click)="goHome()">
              Back to login
            </button>
          </div>
        } @else {
          <app-loading-state
            title="Completing sign-in"
            subtitle="Processing the authorization response."
          ></app-loading-state>
        }
      </app-card>
    </app-shell>
  `,
})
export class AuthCallbackComponent implements OnInit {
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);
  private handled = false;

  error = signal<string | null>(null);

  ngOnInit() {
    if (this.handled) return;
    this.handled = true;
    this.auth
      .handleCallback()
      .then(() => {
        this.router.navigateByUrl("/", { replaceUrl: true });
      })
      .catch((err) => {
        this.error.set(err instanceof Error ? err.message : "Login failed.");
      });
  }

  goHome() {
    this.router.navigateByUrl("/", { replaceUrl: true });
  }
}
